ALTER TABLE quizs ADD COLUMN difficulty INTEGER NOT NULL DEFAULT 1;
ALTER TABLE quizs ADD COLUMN chapter VARCHAR(255) NOT NULL DEFAULT 'Unknown';
ALTER TABLE quizs ADD COLUMN correct_answer_index INTEGER NOT NULL DEFAULT 0;
ALTER TABLE quizs DROP COLUMN correct_answer;