CREATE TABLE quizs (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(255) NOT NULL,
    image_path VARCHAR(255),
    theme VARCHAR(255) NOT NULL,
    question TEXT NOT NULL,
    answers TEXT NOT NULL,
    correct_answer TEXT NOT NULL,
    latex BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE users (
    id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
